### ISSUE TITLE
Error for Facebook test User login

### ISSUE THREAD

**Issue by enessenkg** [jaychang0917/SimpleAuth#12]
I get error while I am testing your application with test user which I generate from facebook developer page. 

Facebook returns json like `{"id":"100579670833398","name":"test locati","email":"test_vpyefuk_locati@tfbnw.net"}`

but library tries to get key `link` which is not included in response...

is this a bug or did I miss something?

**Comment by jaychang0917** [comment]
What is the error message?

**Comment by enessenkg** [comment]
why did not you use optString to get value? [like here](https://developer.android.com/reference/org/json/JSONObject.html#optString(java.lang.String,%20java.lang.String))

**Comment by jaychang0917** [comment]
@enessenkg oh, i didn't know `JSONObject` has such useful method. Thanks reminding me:)

Do you mind to create a PR? or I will fix it tomorrow.
