### ISSUE TITLE
Failed to resolve: com.github.jaychang0917:Utils:0.3.2

### ISSUE THREAD

**Issue by kevin-44** [jaychang0917/SimpleAuth#14]
The build response is now: Failed to resolve: com.github.jaychang0917:Utils:0.3.2

**Comment by kevin-44** [comment]
Aren't you suppose to modify "dependencies.gradle"? The update seems to be solely a version bump.

**Comment by jaychang0917** [comment]
It can't be resolved since the`com.github.jaychang0917:Utils:0.3.2` is on jitpack repository. I have no idea how to tell the bintray to find it on jitpack repo, pls tell me if someone know:)

**Comment by jaychang0917** [comment]
Pls try version `2.0.3`.

**Comment by kevin-44** [comment]
Seems to sync now, hopefully there are no errors. Thanks :)
