### ISSUE TITLE
Instagram login issue

### ISSUE THREAD

**Issue by Rizwanmisger** [jaychang0917/SimpleAuth#19]
Hi,
Instagram login has stopped working for my app. It just opens an empty  webview.
Can you please help with this issue.

Thanks

**Comment by santhoshrao519** [comment]
Me also having same issue along with twitter exception

**Comment by santhoshrao519** [comment]
hey @Rizwanmisger  are you able to solve that? please reply

**Comment by jaychang0917** [comment]
`2.1.2` should fix this issue.

**Comment by santhoshrao519** [comment]
Unable to login through Instagram,
it is redirecting to instagram app when i login. Please fix the issue ASAP,
