### ISSUE TITLE
Google Login

### ISSUE THREAD

**Issue by josempaguiar** [jaychang0917/SimpleAuth#20]
Hi,
When the Google Popup appear to select the Google account and I press back, the Activity becomes empty and the cancel method is not called.
Can you solve this please?
And congratulations for the library it's perfect!

**Comment by sadaq19** [comment]
Hello !
Can you please help me configure Google Signin ? the facebook method work fine but when I call method com.jaychang.sa.google.SimpleAuth.connectGoogle, app crash with error:
ClassNotFoundException: com.google.android.gms.common.api.Api$zzf

**Comment by josempaguiar** [comment]
Hi sadaq19,
You need to add this to your project
implementation "com.google.android.gms:play-services-auth:15.0.1." :)

**Comment by sadaq19** [comment]
Great ! thank you very much, it worked !

**Comment by jaychang0917** [comment]
Version 2.1.3 should fix it.

**Comment by sadaq19** [comment]
Okay ! Thanks again !
