### ISSUE TITLE
Get twitter credentials for firebase auth

### ISSUE THREAD

**Issue by ndptra** [jaychang0917/SimpleAuth#21]
I am currently developing an app that is using firebase auth that has twitter as one of its sign-in methods. The problem is, to sign in with credentials in firebase, we have to get the authToken and Secret. Is there a way to get those 2 properties if I'm using this library? Thanks in advance

**Comment by ndptra** [comment]
Turns out that calling TwitterCore.getInstance().sessionManager.activeSession then get the session's authtoken and secret. Closing this issue

**Comment by AndrewHossam** [comment]
I suggest to add "secret" to SocialUser module , along with accessToken
