### ISSUE TITLE
google account issue

### ISSUE THREAD

**Issue by khem88** [jaychang0917/SimpleAuth#23]
val scopes = Arrays.asList(
                "https://www.googleapis.com/auth/youtube",
                "https://www.googleapis.com/auth/youtube.upload"
        )

        com.jaychang.sa.google.SimpleAuth.connectGoogle(scopes,object :AuthCallback{
            override fun onSuccess(socialUser: SocialUser?) {
                loginStatusListener.onLoginSuccess(socialUser)
                             Log.e("======","Success")
            }

            override fun onCancel() {
                Log.e("======","cancel")
            }

            override fun onError(error: Throwable?) {
                Log.e("======","Google=="+error!!.message)
            }

        })

It return the  onCancel() and print the cancel msg

**Comment by wildfiregt** [comment]
I have the same issue while using Java and latest version of this library

**Comment by sergio11** [comment]
Hi, I have the same problem.

**Comment by nthreads** [comment]
Does anybody manage to resolve this issue?

**Comment by tperraut-geronimo** [comment]
I create a pull request for it #25
