### ISSUE TITLE
Google is not working

### ISSUE THREAD

**Issue by kiyos1221** [jaychang0917/SimpleAuth#3]

**Comment by jaychang0917** [comment]
any error messages?

**Comment by kiyos1221** [comment]
Nothing is displayed, when I call connectWithGoogle it shows the account chooser and stuck there

**Comment by jaychang0917** [comment]
did you try the demo project? is it working?

**Comment by santhoshrao519** [comment]
Google integration is not working.getting following

[GetToken] GetToken failed with status code: BadAuthentication

[GoogleAccountDataServiceImpl] getToken() -> BAD_AUTHENTICATION. Account: <ELLIDED:-1551497223>, App: com.android.vending, Service: androidmarket
                                         fbl: Long live credential not available.

**Comment by jaychang0917** [comment]
pls provide the demo project

**Comment by santhoshrao519** [comment]
i have used the same library as demo, even though it is showing above error. please help

**Comment by jaychang0917** [comment]
did you try with another device?

**Comment by santhoshrao519** [comment]
ya, i have tried on different devices,

**Comment by jaychang0917** [comment]
debug build variant? correct SHA1?

**Comment by santhoshrao519** [comment]
i have tried with release build and correct sha1

**Comment by jaychang0917** [comment]
your issue looks similar to [this](https://stackoverflow.com/questions/35967017/gettoken-failed-status-bad-authentication-error)

**Comment by santhoshrao519** [comment]
do i really need to add google-services.json file in my app?

**Comment by jaychang0917** [comment]
no need

**Comment by jaychang0917** [comment]
did you try this repo demo? is it working?

**Comment by santhoshrao519** [comment]
no, it is not showing when i click on "Connect Google" green button. It is just showing list of google accounts, but when i clicked on a account, nothing happens

**Comment by jaychang0917** [comment]
you're using Android Studio 3.0+?

**Comment by santhoshrao519** [comment]
yes android studio 3.0.1

**Comment by jaychang0917** [comment]
I have no idea... I just tried this repo demo with debug build variant in two devices, works as expected.

**Comment by santhoshrao519** [comment]
okay, please do share debug build instructions for sha1 key and client auth id.

**Comment by jaychang0917** [comment]
clone this repo, then build

**Comment by santhoshrao519** [comment]
i have downloaded and imported this project into studio but when i click on google button, still not working

**Comment by santhoshrao519** [comment]
do i need to change googleWebClientId in build.gradle file when i download this repo?

**Comment by n1k3c** [comment]
any update?

**Comment by santhoshrao519** [comment]
Not working yet..

On Jan 6, 2018 07:53, "Nikola Curilovic" <notifications@github.com> wrote:

any update?

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/jaychang0917/SimpleAuth/issues/3#issuecomment-355716281>,
or mute the thread

**Comment by jaychang0917** [comment]
@santhoshrao519 
> do i need to change googleWebClientId in build.gradle file when i download this repo?

no need

using a real device (which model?) or emulator?

**Comment by santhoshrao519** [comment]
Real device..samsung

**Comment by jaychang0917** [comment]
which model?

**Comment by santhoshrao519** [comment]
Samsung Galaxy s6 edge..not even working on other. Mobiles too

**Comment by jaychang0917** [comment]
what is your android debug keystore sha1?
`keytool -exportcert -keystore ~/.android/debug.keystore -list -v`

**Comment by jaychang0917** [comment]
You must
- use a google **WEB** client id **AND**
- create an **Android** oauth client, and fill out your correct sha1 and package name

**Comment by santhoshrao519** [comment]
I did as same for many times ...but no luck

**Comment by jaychang0917** [comment]
@santhoshrao519 if you're testing this repo demo, you may provide me your android debug keystore sha1. I am not sure if the sha1 is same

**Comment by mikrop** [comment]
Hi @jaychang0917 i have the same problem,

1) Do I Generate Client ID Well? https://github.com/mikrop/uctenkova-smenarna-android/blob/master/Bez%20n%C3%A1zvu.png
2) When I put a custom googleWebClientId into the build.gradle file
3) I will overwrite package = "cz.mikropsoft.android.uctenkovka.smenarna" in AndroidManifest.xml
4) I will deploy an application to my phone and debug responce, I get the com.jaychang.sa.GoogleAuthActivity # onActivityResult parameter resultCode = 0 (operation canceled).

What am I doing wrong? Thank you for answer! Michal

**Comment by jaychang0917** [comment]
@mikrop using a web client id? Don't use android client's one

**Comment by mikrop** [comment]
It works! Thank you

**Comment by jaychang0917** [comment]
I closed it. Please feel free to reopen the issue if you have any questions.

**Comment by santhoshrao519** [comment]
Hi Jay,
Facing an issue while login with google+. When a select a user email from the list, nothing happens

**Comment by sergio11** [comment]
@jaychang0917 @santhoshrao519
I am experiencing the same problem a few days ago. I have not changed anything at all (the Google Play Services version is the same) and it has stopped working. I upload the following image so you can see the response of the API.

![image](https://user-images.githubusercontent.com/6996211/56439876-ef1af700-62e7-11e9-8f41-ca256f2b1574.png)

**Comment by sergio11** [comment]
I have tried everything:

- Clean project and rebuild.
- Reboot device.
- Review states of synchronized accounts.
- I have reviewed the SHA1 and the application id. Use the client_id for type 3.
- I have tried to rewrite the authentication with the new API and it also returns the same error as before.
