### ISSUE TITLE
Able to get profile information from all social sites but getting unmarshalling exception while sending profile data to server

### ISSUE THREAD

**Issue by santhoshrao519** [jaychang0917/SimpleAuth#4]
I'm able to get profile info from facebook and twitter, but when i'm sending that data to server it is showing following error.

Failed to parse Bundle, but defusing quietly
                                          android.os.BadParcelableException: ClassNotFoundException when unmarshalling

**Comment by jaychang0917** [comment]
Can you provide a demo project that can reproduce the issue?

**Comment by santhoshrao519** [comment]
I can't provide the demo, as i'm working on a client project,

**Comment by jaychang0917** [comment]
can you provide a more detail log?

**Comment by santhoshrao519** [comment]
when i'm sending profile data such as name, email, userid, pic from the socialuser to php server
the app is throwing exception.

**Comment by jaychang0917** [comment]
I think it may be your server issue.  can you provide the error stacktrace?

**Comment by jaychang0917** [comment]
I closed it. Please feel free to reopen the issue if you have any questions.
