### ISSUE TITLE
Usage with multiple facebook id's in flavors

### ISSUE THREAD

**Issue by ghost** [jaychang0917/SimpleAuth#6]
Hi,

Thanks for such useful library!

Our project have multiple "White Label" apps. In other words is multi flavor app.
For each flavor we need distinct facebook id.
Is there a way to define distinct id's for each flavors?

Thanks!

**Comment by jaychang0917** [comment]
should be
```gradle
android.productFlavors.findByName("flavorA").manifestPlaceholders = [
    facebookAppId        : "flavorA facebook app id"
]
android.productFlavors.findByName("flavorB").manifestPlaceholders = [
    facebookAppId        : "flavorB facebook app id"
]
```

**Comment by ghost** [comment]
Thanks for help!

I will try it )))))
