### ISSUE TITLE
Could not determine artifacts after upgrade AS to 3.1

### ISSUE THREAD

**Issue by ghost** [jaychang0917/SimpleAuth#9]
Hi,

Output errors:

`
Could not resolve all dependencies for configuration ':app:chfQaRuntimeClasspath'.
Could not determine artifacts for com.jaychang:simpleauth:2.0.1
Could not get resource 'https://jcenter.bintray.com/com/jaychang/simpleauth/2.0.1/simpleauth-2.0.1.aar'.
Could not HEAD 'https://jcenter.bintray.com/com/jaychang/simpleauth/2.0.1/simpleauth-2.0.1.aar'. Received status code 502 from server: Bad Gateway

`
Also for 2.0.0 version ))

Thanks!

**Comment by ZaydelEduard** [comment]
I'm using AS 3.1 and everything works fine.

**Comment by ghost** [comment]
Hi,

It was not related to your library but AS 3.1 issue!

Thanks!
